jQuery(document).ready(function($) {
	jQuery('#grid').jqGrid({					
		"width":"650",
		"hoverrows":true,
		"viewrecords":true,
		"jsonReader":{
			"repeatitems":false,
			"subgrid":{
				"repeatitems":false
			}
		},
		"xmlReader":{
			"repeatitems":false,
			"subgrid":{
				"repeatitems":false
			}
		},
		"gridview":true,
		"url":"myfirstgrid.php",
		"editurl":"myfirstgrid.php",
		"cellurl":"myfirstgrid.php",
		"caption":"This is custom Caption",
		"rowNum":10,
		"sortname":"OrderID",
		"rowList":[10,20,50],
		"datatype":"json",
		"colModel":[
			{
				"name":"OrderID",
				"index":"OrderID",
				"editable":true,
				"sorttype":"int",
				"key":true,
				"label":"ID",
				"width":60
			},
			{
				"name":"OrderDate",
				"index":"OrderDate",
				"editable":true,
				"sorttype":"datetime",
				"formatter":"date",
				"formatoptions":
				{
					"srcformat":"Y-m-d H:i:s","newformat":"m/d/Y"
				}
			},
			{
				"name":"CustomerID",
				"index":"CustomerID",
				"editable":true,
				"sorttype":"string"
			},
			{
				"name":"Freight",
				"index":"Freight",
				"editable":true,
				"sorttype":"numeric"
			},
			{
				"name":"ShipName",
				"index":"ShipName",
				"editable":true,
				"sorttype":"string"
			}
		],			
		"postData":{"oper":"grid"},
		"prmNames":
		{
			"page":"page",
			"rows":"rows",
			"sort":"sidx",
			"order":"sord",
			"search":"_search",
			"nd":"nd",
			"id":false,
			"filter":"filters",
			"searchField":"searchField",
			"searchOper":"searchOper",
			"searchString":"searchString",
			"oper":"oper",
			"query":"grid",
			"addoper":"add",
			"editoper":"edit",
			"deloper":"del",
			"excel":"excel",
			"subgrid":"subgrid",
			"totalrows":"totalrows",
			"autocomplete":"autocmpl"
		},
		"loadError":function(xhr,status, err){ 
			try {
				jQuery.jgrid.info_dialog(jQuery.jgrid.errors.errcap,'<div class="ui-state-error">'+ xhr.responseText +'</div>', jQuery.jgrid.edit.bClose,{buttonalign:'right'});
			} 
			catch(e) { alert(xhr.responseText);} 
		},
		"pager":"#pager"
	}); 
});